
networks:
  limiter:
    external: false

services:
  redis:
    image: redis:7
    container_name: rate_limiter_redis
    ports:
      - "6379:6379"
    networks:
      - limiter
    command: redis-server --requirepass sysdba
  
  app:
    container_name: app_rate_limiter
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    networks:
      - limiter
